
POST  http://localhost:3000/relocations/
Content-Type: application/json

{
  "civilite": "Monsieur",
  "nom": "Coulibaly", 
  "prenom": "Souleymane",
  "telephone": "0669444719",
  "Email": "s.coulibaly@outlook.com",
  "date": "20202-10-22",
  "adresseDepart": "12 résidence les taratres rueil malmaison",
  "nbreEtageDepart": 5,
  "ascenseurDepart": true,
  "adresseArrivee": "28 rue thiers Belfort",
  "nbreEtageArrivee": 2,
  "ascenseurArrivee": false,
  "volume": 55,
  "distanceDePortage": 300,
  "prestationComplementaire": "FOURNITURES D'EMBALLAGE"
}